### ISSUE TITLE
Change icon when icon is empty

### ISSUE THREAD

**Issue by Straskal** [armandoalonso/c3IDE#60]
Somehow, my addon icon became empty | null! Oh noooo.

Now when I go to change it I get the following exception:

```
There was an unhandled error in the application. see logs below => 
ERROR MESSAGE => Reference to undeclared entity 'raquo'. Line 27, position 79.
ERROR TRACE =>    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at Svg.SvgTextReader.Read()
   at Svg.SvgDocument.Open[T](XmlReader reader)
   at Svg.SvgDocument.Open[T](Stream stream, Dictionary`2 entities)
   at Svg.SvgDocument.Open[T](Stream stream)
   at c3IDE.Utilities.Helpers.ImageHelper.SvgFromXml(String xml)
   at c3IDE.Windows.AddonIconWindow.Init(String iconXml)
   at c3IDE.Windows.DashboardWindow.ChangeAddonIcon_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
ERROR INNER EX => 
ERROR SOURCE => System.Xml

EXCEPTION LIST =>
```

**Comment by armandoalonso** [comment]
i am not able to reproduce this? i added some exception handling & logging around this so if it happens again, please post the new log here. it will help me better understand whats going on

**Comment by skymen** [comment]
Made it possible to drag and drop new icons when the XML fails to load properly.
Also made it possible to reset to the default icon in case of error.
https://github.com/armandoalonso/c3IDE/pull/74

In another PR I fixed issues with loading and drawing SVGs, chances are it also fixed part of the issue
https://github.com/armandoalonso/c3IDE/pull/72
